### ISSUE TITLE
'Filters' misidentifies characters with combining diacritics

### ISSUE THREAD

**Issue by Neonnaut** [bbrk24/lexifer-ts#10]
If I give it the input:
```
words: r̈ é
filter: r > rr;  e>ee;
```
where ⟨r̈⟩ has a combining diacritic, but ⟨é⟩ is it's own single character,
I get the results `rr̈ é`.
So ⟨r̈⟩ is being confused with ⟨r⟩ and getting an unexpected result.

**Comment by Neonnaut** [comment]
I've been able to resolve this by placing:
`newWord = newWord.replace(new RegExp(pat, 'gu'), repl);` in the `applyFilter()` function into an if statement comparing tring length:
```
if (newWord.length === pat.length) {
    newWord = newWord.replace(new RegExp(pat, 'gu'), repl);
}
```

**Comment by Neonnaut** [comment]
I had a look at what was causing it, it's `newWord = newWord.replace(new RegExp(pat, 'gu'), repl);` in the `applyFilter(pat, repl)` function.

it's treating the combining diacrritic as if it's it's own char, so it's treating it like `r◌̈`, and then the filter is matching it to the `r` but leaving the diacritic. I don't think there is a simple fix to it.

**Comment by bbrk24** [comment]
I think I'm going to close this as expected behavior. If you really want to only grab non-diacritic'd versions of a letter, I think adding `(?=\w|$)` should work (followed only by another letter or the end of a word), but I haven't tested that.

**Comment by Neonnaut** [comment]
>  If you really want to only grab non-diacritic'd versions of a letter...

That wasn't the issue, I think you've misunderstood.

**Comment by Neonnaut** [comment]
`(?=\w|$)` would definitely not work as it wouldn't deal with special characters like "ɕ"

**Comment by Neonnaut** [comment]
Sure this
```
words: r̈ é
filter: r(?=\w|$) > rr;  e>ee;
```
works. It should be included in the documentation somewhere.
