### ISSUE TITLE
Generating something, then generating from a blank file, then generating again... only generates macros

### ISSUE THREAD

**Issue by Neonnaut** [bbrk24/lexifer-ts#11]
This is happening on both my own implementation of it, and on https://lingweenie.org/conlang/lexifer-app.html.

It's happening in Chrome, Safari and Firefox.

How to produce error: 
1. Generate some words, from for example this file:
```
C = t n k p
D = n ʔ
V = a i e u o

$S = CVD?

words: V?$S$S V?$S V?$S$S$S
```
2. Generate words from an empty file, getting the "Error: Please include a definition." error.
3. Replace the file with the exact same content as in step 1.
4. Generate words. I get results that look like:
```
CVCVCV CVCVD CV CVCV CV CVCV, CV CV VCVCVD. CVCV CVCV
```

If I keep generating words, I get the same results. But if I change the content in the file, it works as normal again.

Quite strange.

**Comment by bbrk24** [comment]
I think I know why this is happening and it's a really stupid mistake. I could make a commit that fixes this easily but pushing that fix to the website would take longer.

**Comment by bbrk24** [comment]
I think 224751bbf20182df82d54dca47e6f9e3c7936a12 should fix this, but it won't be on the website until late next week.

**Comment by Neonnaut** [comment]
Nice, it does fix it. I assume there is a reason you don't just reset the cache upon getting an error.

**Comment by bbrk24** [comment]
The hash thing was unsound anyways. A hash can tell "definitely distinct" or "probably the same", and I was trying to use it for "definitely the same" vs "probably distinct".

**Comment by bbrk24** [comment]
The changes should be live now. Can you confirm the issue no longer occurs?

**Comment by Neonnaut** [comment]
the issue no longer occurs on lingweenie website.
