### ISSUE TITLE
Filter not working (maybe I'm using wrongly the cluster fields)

### ISSUE THREAD

**Issue by nekoniyah** [bbrk24/lexifer-ts#3]
Here is my current code, and the filter / rejects don't work. Please help me.

`with: std-ipa-features std-assimilations coronal-metathesis

letters: l j kj w ʃ v s r h b d g m n p t k a i e o u

C = l j kj w ʃ v s r h b d g m n p t k
D = l j w ʃ v s r h b d g m n p t k
V = a i e o u

% l j kj w ʃ v s r h b d g m n p t k
l + + + + + + + - + + + + + + + + +
j + - + + + + + + - - + + + + - + +
w - - - - + - + - - - - - - - - - -
ʃ + + + + - - - + - - + + + + + + + 
v + - - - - - - + - - + + + + - - - 
s + + + + - - - + - - - - + + + + +
r - + - + - + + - + + + + + + + + +
h - - - - - - - - - - - - - - - - -
b + - - - - + - + - - - - + - - - -
d - - - - - + - + - - - - - + - - -
g + - - gu - + - + - - - - - + - - - 
m - - - - - - - - - + - - - - + - -
n - - - - - - - - - - + + + - - + +
p + - + - - - + + - - - - + - - + -
t - - + - + - + + - - - - - + - - -
k + q q qu + - + + - - - - - + - - -

$S = CVD?

words: V?$S$S V?$S V?$S$S$S

reject: (..+)\1+

reject: wu yi iy qi quu w$ iy$
filter:  ŋ > n; kj > q; j > y; ʃ > sh;`

**Comment by bbrk24** [comment]
Tip: you need three backticks, not just one, if the code spans multiple lines.

I seem to remember there was a weird bug where any trailing whitespace in a cluster field would break the parser. I thought I fixed it, but maybe I never published the fix; could you check if it's that?

**Comment by nekoniyah** [comment]
Hmmm. A moment, I think I tried to remove the whitespaces and it still didn't work

**Comment by nekoniyah** [comment]
```
with: std-ipa-features std-assimilations coronal-metathesis

letters: l j kj w ʃ tʃ v s z r h b d g m n p t k a i e o u

C = l j kj w ʃ v s z r tʃ h b d g m n p t k
D = l j w ʃ v s r h b d g m n p t k
V = a i e o u

% l j kj w ʃ v s r h b d g m n p t k z tʃ
l + + + + + + + - + + + + + + + + + + +
j + - + + + + + + - - + + + + - + + + +
w - - - - + - + - - - - - - - - - - - -
ʃ + + + + - - - + - - + + + + + + + - -
v + - - - - - - + - - + + + + - - - + -
s + + + + - - - + - - - - + + + + + - -
r - + - + - + + - + + + + + + + + + + -
h - - - - - - - - - - - - - - - - - - -
b + - - - - + - + - - - - + - - - - + -
d - - - - - + - + - - - - - + - - - + -
g + - - gu - + - + - - - - - + - - - + -
m - - - - - - - - - + - - - - + - - + -
n - - - - - - - - - - + + + - - + + + +
p + - + - - - + + - - - - + - - + - - -
t - - + - + - + + - - - - - + - - - - -
k + q q qu + - + + - - - - - + - - - - -
z + + - - - + - + - + + + + + - - - - -
tʃ - - -  - - - - - - - - - - - - - - - -

$S = CVD?

words: V?$S$S V?$S V?$S$S$S

# haplology
reject: (..+)\1+

reject: wu yi iy qi kq f ʒ quu w$ iy$
filter: ŋ > n; kj > q; j > y; ʃ > sh; tsh > c
```

Lali vaya asho ca? Qa wama, lava yasi qeqabu bayi sha la leha yiro
lado. Avalusa shoshu shiza ye sehishlab. Yene lashe yobal di abo rerze
shishuwa, yeshi. Waci wale su shayaral nime, wazado wala lishi. Lul
lawi lu li wa liwa ride, veshi shoheshi qa. Dasi wa gici wele yo, wa
qeyali ve. Yole ya ali valo liqa hise lowayi resem, lisa qey yola.
Zosa sa leri hiywa capaza ya oqelaqa. Wayewsha le rave zo yawa be qa.
Ga siwani sha va ikusa, laga ceso bishahe yolshowi seyca. Lelayo liqa
di yiqa shisa qov. Ni waqozi qali oca, noba yiqa waylama zeba lashi
ashala. Qa qosha la hish yiyo va heqawa yi, yaqa so zov? Yisha rorvili
shiqa alila lasizu qewelu. Recasa va wabilo lasha cowi zoya sha, yeyi
ziya. Caqas la osha zozav. Uleya sheshuwe yeshaqa, yeva raha wi sashi
woya wa laca lavi. Yey di, rizuce zahe laqu walu bi shagale oyusha
bawa? Yashi so qav lebishu yarwi shiyi civa yaqo lama ziye valwa,
qeva. Sica gayeli leloha lashra luh, doqa silare qoza qaza. Yiri mare
eyabaya wi lo, aho yobi yi. Alisha vewa macahi ora ya, cusha shawi
savalag sosho hayi. Wi qa bola iyose shavay li lowo, aqaya la yayisa
lelsho. Za shawame lar da ga yayeqo widal hi so so, sa.

**Comment by nekoniyah** [comment]
Oh no a whitespace remains? I removed it, and It seems working well.

**Comment by nekoniyah** [comment]
Yepo qo azeye baci za qaza. Quri ri lel sawi qa. Vamila shizbav wisi,
laho yavi ye giy dasa sasoqo shab savi shiyilo. Lasade ilayze ya welva
buye yalu gazden shaqa eyasho, shiyu yavela zal. Wa yal salwev zeqa
wiyeba. Ril awa wa wid? Loda sagi yapi lo layqa wiy sevar, yala yavi
gisa? Laga lara hawo yay za luva zaho, zoya bayaca qag? Owole yul
lishlev la yala qaya, qay shilqesler? Liwaksha sha zeshlah su. Yogela
lor lawi acaru vacu lel? Ya ehawa liwshiv, beyi aqazigi welhaklal leg
ilalli. Qashesha hoyes, dish boca iqaya liyuwo zayle qa woy qadube yo
volshal. Qe lallim yalyaryel ga sharyo. Qowa arica cemi vara? Shoviy
zaqa qel zezi ray yov. Laya baso, lisi wiyah ya qeshwir ashala
zilshiblab lu sa aqo. Rawa salqabzin lullalbab yaqa. Qa sayi qali ciqa
qacashe, la kihipi qe. Deshludrash za wali yi, qaza co shali qave
vala. Esa lashqom abile woydish. Osehi qa lish lorver ra shiceve yu,
neyrash? Zava yalo ural resh qeki, lezi yuliga ilarasi shiyal dakrali.
Ga qa qal zova eviwe qawo, mar shala rih woksha yeyi lowi? Qashi qusig
weya zal yari reyala loldih.

Ah no, it still doesn't work

**Comment by nekoniyah** [comment]
I found out the problem

**Comment by nekoniyah** [comment]
As "reject" is converted as a "filter", it is put at the start of the filters. So the "y" isn't here yet, so I replaced the "y" by a "j" and it works well now.

**Comment by nekoniyah** [comment]
```
with: std-ipa-features std-assimilations coronal-metathesis

letters: l j kj w ʃ tʃ v s z r h b d g m n p t k a i e o u

C =l j kj w ʃ v s z r tʃ h b d g m n p t k
D =l j w ʃ v s r h b d g m n p t k
V =a i e o u

% l j kj w ʃ v s r h b d g m n p t k z tʃ
l + + + + + + + - + + + + + + + + + + +
j + - + + + + + + - - + + + + - + + + +
w - - - - + - + - - - - - - - - - - - -
ʃ + + + + - - - + - - + + + + + + + - -
v + - - - - - - + - - + + + + - - - + -
s + + + + - - - + - - - - + + + + + - -
r - + - + - + + - + + + + + + + + + + -
h - - - - - - - - - - - - - - - - - - -
b + - - - - + - + - - - - + - - - - + -
d - - - - - + - + - - - - - + - - - + -
g + - - gu - + - + - - - - - + - - - + -
m - - - - - - - - - + - - - - + - - + -
n - - - - - - - - - - + + + - - + + + +
p + - + - - - + + - - - - + - - + - - -
t - - + - + - + + - - - - - + - - - - -
k + q q qu + - + + - - - - - + - - - - -
z + + - - - + - + - + + + + + - - - - -
tʃ - - - - - - - - - - - - - - - - - - -

$S = CVD?
$Z = CVD

words: V?$S$S V?$Z$Z V?$S V?$Z V?$S$S$S V?$Z$Z$Z

reject: wu ji ij qi kq f ʒ quu w$ (..+)\1+
filter: ŋ > n; kj > q; j > y; ʃ > sh; tsh > c
```

**Comment by bbrk24** [comment]
To be clear, is your problem resolved now?

**Comment by nekoniyah** [comment]
Yep
