### ISSUE TITLE
[Bug] When setting number of word (paragraph mode), every word starts with the same letter

### ISSUE THREAD

**Issue by nekoniyah** [bbrk24/lexifer-ts#4]
![image](https://github.com/bbrk24/lexifer-ts/assets/114854571/4fc2d730-0237-4bcb-8f2a-21f60d471d53)
Hello, here is an example of the bug can it be fixed ?

**Comment by bbrk24** [comment]
I don't see the issue. The words don't look like they all start with the same letter. What is the expected behavior, and how does it differ from what you're actually seeing?

**Comment by nekoniyah** [comment]
Look 
![image](https://github.com/bbrk24/lexifer-ts/assets/114854571/3711d6f7-84bc-4f49-ab42-7d3561f7ab93)
the p is shown here not somewhere else, 
![image](https://github.com/bbrk24/lexifer-ts/assets/114854571/26bd1241-2c50-47da-9bf7-6e5c9deda69d)
Look the number of words starting with s cedilla!

**Comment by bbrk24** [comment]
> the p is shown here not somewhere else,

You haven't checked "leave output unsorted", so it's alphabetizing the output.

> Look the number of words starting with s cedilla!

This is more likely the fault of your language definition than a bug in the software.

**Comment by nekoniyah** [comment]
Alright, thx ! I'll unsort the output. Yes I added the s cedilla but I
think the count is random!..
