### ISSUE TITLE
Whitespace in cluster header issue

### ISSUE THREAD

**Issue by Neonnaut** [bbrk24/lexifer-ts#5]
It seems if I have a cluster table like:

```
%  p t 
a + -
e - -
```
And put a space after 't', It says `Error: cluster field row too short`.

Putting a space after '-' etc is fine though.

**Comment by bbrk24** [comment]
I've seen this issue before. I thought I fixed it already.

**Comment by bbrk24** [comment]
I just checked, a fix already exists, but lingweenie.org doesn't have the most up-to-date version of the script.

**Comment by bbrk24** [comment]
lingweenie.org now has the most up-to-date version.

**Comment by Neonnaut** [comment]
nice
